akka/akka-persistence-r2dbc

- .github/workflows/build-test.yml
- .github/workflows/publish.yml
- .gitignore
- .jvmopts-ci
- .scalafmt.conf
- CONTRIBUTING.md
- LICENSE
- build.sbt
- docker/docker-compose-postgres.yml
- docs/src/main/paradox/.htaccess
- docs/src/main/paradox/_template/projectSpecificFooter.st
- docs/src/main/paradox/assets/js/warnOldVersion.js
- docs/src/main/paradox/contributing.md
- docs/src/main/paradox/index.md
- docs/src/main/paradox/overview.md
- project/AutomaticModuleName.scala
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
- project/project-info.conf
* copied from akka-persistence-spanner
> Initial build infra

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/ContinuousQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/resources/logback-test.xml
- core/src/test/scala/akka/persistence/r2dbc/TestActors.scala
- core/src/test/scala/akka/persistence/r2dbc/TestConfig.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/ContinuousQuerySpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
* since each query result is materialized in memory we
must have a limit on the result set
* ContinousQuery allow for defining the delay and next query
based on number of elements found in previous query
* Query more when reaching the limit (buffer-size)
> Read in chunks

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_yugabyte.sql
* because transaction_timestamp() is when the transaction started, not when it was
committed and therefore it is possible to miss events when reading at the very
end of the tail
* this is probably not the final (full) solution to this problem, since it's
hard to know how long the delay should be to be safe
* it's a first quick improvement to that problem, and akka-projection-testing
is passing with this, which it didn't before
* like eventual consistency delay
> Read behind current timestamp

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/main/scala/akka/projection/r2dbc/scaladsl/R2dbcProjection.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcProjectionSpec.scala
* that was already the case but unclear since projectionId
was used as parameter to the OffsetStore methods
* projectionId as constructor parameter instead
> One OffsetStore per projectionId

- ddl-scripts/create_tables_postgres.sql
- projection/src/main/resources/reference.conf
- projection/src/main/scala/akka/projection/r2dbc/R2dbcProjectionSettings.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/test/resources/logback-test.xml
- projection/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/TestDbLifecycle.scala
* store TimestampOffset in separate table, with one row per
persistence_id to keep track of sequence_number
* the pid/seqNr State will be used to filter duplicates
* keep a time window in memory and database
* db deletes in the background
* consumer lag can be seen from last_updated - timestamp_offset
> OffsetStore for TimestampOffset

- projection/src/test/scala/akka/projection/r2dbc/ChaosSpec.scala
I definitely saw one test failure that could be explained by 16 events on the same timestamp.
I don't think this explains all of https://github.com/akka/akka-persistence-r2dbc/issues/44
> Increase buffer-size in ChaosSpec

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/R2dbcDurableStateStore.scala
- ddl-scripts/create_tables_yugabyte.sql
As can be seen in #97 the query logic for events and durable state are pretty much identical. This moves that to a common generic class.
I have only extracted one of four so far and would like feedback before completing.
> Extract common by slice query logic

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
This is a follow up on https://github.com/akka/akka-persistence-r2dbc/pull/99
* The inflight Map(pid->seqNr) is needed for atLeastOnce or other projections
that store the offset afterwards. When using the retry mechanism the Map should
not be updated so that next retry can accept the envelope.
* Changed the isAccepted method to be pure (returning Boolean without side effect)
and separate addInflight for the modification. That is better design in general,
and makes it possible to only add to the inflight Map after successful processing
instead of the revert mechanism that was implemented previously.
* Also combined isDuplicate and isAccepted into one method since they are always used
together.
References #31
> Make inflight more robust, #31

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/query/scaladsl/EventTimestampQuery.scala
- core/src/main/scala/akka/persistence/query/scaladsl/EventsBySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
- projection/src/main/resources/reference.conf
- projection/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider2.scala
- projection/src/main/scala/akka/projection/r2dbc/R2dbcProjectionSettings.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/main/scala/akka/projection/r2dbc/scaladsl/R2dbcProjection.scala
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
This became rather invasive but I'm quite convinced that it's needed.
* When the offset store receives an unknown sequence number
in `isAccepted` it will try to lookup the timestamp of the
previous event. If that is older than then time window of
the offset store it will be accepted, otherwise rejected.
* The reason for rejecting is that it previous event could
be missing when reading from the tail based on the latest
timestamp offset.
* Backtracking will pick up the missing event and fill the
gap.
* This is better than the previous accept-new-sequence-number-after-age
(3 seconds) because it will not introduce that delay for the
"normal case" when a new event is emitted and previous event
was older than the offset store time window.
* Also, previous solution had the the uncertainty about …
> Lookup timestamp of previous sequence number, #74

- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/R2dbcJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/R2dbcSnapshotStore.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/SnapshotDao.scala
* to release the connection as quickly as possible
* reuse the currentEventsByPersistenceId query also for the
journal replay
* serialization moved out from the SnapshotDao,
as a separation of concerns, and to align with JournalDao
> Move deserialization of journal row out from connection block

- build.sbt
- core/src/test/scala/akka/persistence/r2dbc/TestActors.scala
- core/src/test/scala/akka/persistence/r2dbc/TestConfig.scala
- migration/src/main/resources/reference.conf
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationTool.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationToolDao.scala
- migration/src/test/resources/application.conf
- migration/src/test/resources/logback-main.xml
- migration/src/test/scala/akka/persistence/r2dbc/migration/MigrationToolSpec.scala
- project/Dependencies.scala
* It has been tested with akka-persistence-jdbc as source plugin, but it should
work with any plugin that has support for `CurrentPersistenceIdsQuery` and
`CurrentEventsByPersistenceIdQuery`
* It can be run while the source system is still active and it can be run multiple
times with idempotent result.
> Migration of events and snapshots from any Akka Persistence plugin

- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
* flaky in CI
* I looked at logs from one of the failed runs and it was missing 1 event for the
"Live eventsBySlices should retrieve from several slices", couldn't see
a reason from the logs
References #118
> Harden EventsBySliceSpec, #118

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
* <= instead of <
* because otherwise the backtracking will not find the last event
if there is no other progress
See description of test that failed https://github.com/akka/akka-persistence-r2dbc/issues/109#issuecomment-967208120
Fixes #109
> Backtrack to the ordinary timestamp, #109

- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/TestSourceProviderWithInput.scala
* problem was that projectionTestKit.run resets the OffsetStore for each
run and therefore the inflight was not kept
* use a new TestSourceProvider that can be feeded with
envelopes rather than just emitting a fixed collection
I might rewrite some of the other tests that could have similar async problem (even though we might not have seen it yet).
Fixes #147
> Rewrite test for grouped async, #147

- .github/workflows/build-test.yml
- .github/workflows/publish.yml
* because the version becomes a time snapshot when publishing
> Don't copy .jvmopts-ci

- core/src/main/scala/akka/persistence/r2dbc/snapshot/SnapshotDao.scala
* because there is only one row per persistenceId
I don't expect this to make any performance difference.
> remove order by in snapshot sql

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/SnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/test/resources/logback-test.xml
- core/src/test/scala/akka/persistence/r2dbc/TestDbLifecycle.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationTool.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationToolDao.scala
- projection/src/main/resources/reference.conf
- projection/src/main/scala/akka/projection/r2dbc/R2dbcProjectionSettings.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/main/scala/akka/projection/r2dbc/scaladsl/R2dbcProjection.scala
- projection/src/test/scala/akka/projection/r2dbc/TestDbLifecycle.scala
it can also be good to know that logging of slow queries can be enabled on the Yugabyte server side: https://docs.yugabyte.com/latest/explore/query-1-performance/query-tuning-intro/#log-slow-queries
> config setting for logging of (slow) db calls

- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_yugabyte.sql
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
* should make the deletes <= timestamp faster since
it can use the prefix of the primary key
* note that primary key of akka_projection_timestamp_offset_store
was changed, so existing tables must be recreated (can be populated
with old data with 'insert into .. select * from'
References #106
> Insert offset instead of upsert, #106

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/ConnectionFactoryProvider.scala
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
* when database server is restarted all connections in the
pool are invalid and that is not detected until they are
acquired
* validation of the connection is performed by the
pool on create and it will retry with the configured
acquire-retry
* added validation-query config
Fixes #157
> Adjust config to reduce connection errors, #157

- docker/docker-compose-yugabyte.yml
* current stable release
Yugabyte is using even versions for stable production releases
https://docs.yugabyte.com/latest/releases/versioning/
2.8 was released Nov 15
> Yugabyte 2.8.0.0-b37

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/R2dbcJournal.scala
* as temporary workaround for performance testing
> Option to use application timestamp

- core/src/main/scala/akka/persistence/r2dbc/ConnectionFactoryProvider.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- project/Dependencies.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
* stmt .add() must not be at the end, any more
* workaround for connection pool bug when maxLifeTime isn't set
* verified that performance is the same
> Update to R2DBC 0.9.0

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreStateSpec.scala
* when same timestamp the order of added records were not taken
into account
* when reading from db the records are not ordered
* keep latest seqNr in the seen map of latestOffset
* unit test of R2dbcOffsetStore.State
Fixes #173
> fix highest seqNr in seen of latestOffset, #173

- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
* not needed in WHERE any more since persistence_id is the primary key
Leftover from https://github.com/akka/akka-persistence-r2dbc/pull/177
> cleanup some more slice and entity_type columns

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/ContinuousQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/BySliceQueryBucketsSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/journal/TestDataGenerator.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_yugabyte.sql
* reduce result set that is sorted before limit is applied
* fetch event counts in buckets with aggregate query and use that
to estimate the `db_timestamp < ?` that is needed to reach the limit
* also include some more columns in index to make the backtracking
query IndexOnly Scan (no fetch from parent table)
Fixes #178
> Upper bound on db_timestamp in eventsBySlices query, #178

- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
* don't include the getConnection duration in the db call measurement
* getConnection has it's own measurement
> Separate getConnection and db call measurement (logging)

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/ConnectionFactoryProvider.scala
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
* Even though idle connections are evicted from the pool it's
likeley that connections in the pool are "touched" also during infrequent usage,
i.e. they are not idle.
* By setting the max-life-time the connections are cycled out from the pool and
the number of connections in the pool will shrink, as long as there is not demand
for more connections.
I tested this with R2dbcJournalPerfManyActorsSpec by adding a "slow" phase at the end. Also added some temporary debug logging in r2dbc-pool `evictionPredicate`.
Number of connections can be seen with:
```
SELECT count(*)
FROM   pg_stat_activity
WHERE  datname = current_database()  -- only current database
AND    pid <> pg_backend_pid()
```
> Set max-life-time to shrink pool

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/ConnectionFactoryProvider.scala
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
* createTimeout is just a timeout on the Mono, but the underlying connection may still be established
and not closed
* use ConnectionFactoryOptions.CONNECT_TIMEOUT instead
* also change acquire-retry to 1, and mention that it can be increased
Fixes #182
> Fix connection leak caused by create-timeout, #182

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
* if envelope is "marked" with NotUsed in the eventMetaData
> A way to skip envelopes but still store offset

- projection/src/main/resources/reference.conf
- projection/src/main/scala/akka/projection/r2dbc/R2dbcProjectionSettings.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreStateSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
* found this issue and also unique constraint violations when
replaying projection from beginning and the events were stored
with rather low frequency, i.e. many events but not that many per second
* what happended was that the events from backtracking were received after
corresponding original event had been evicted from the store and then
it was accepted (duplicate)
> Less aggressive eviction

- core/src/main/resources/reference.conf
* Noticed that EventSourcedPubSubSpec was flaky
Dedup was added in https://github.com/akka/akka-persistence-r2dbc/pull/248
> Disable deduplication for publish-events by default

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
This was noticed as a problem with atLeastOnceFlow but could probably happen with other async projections as well.
The scenario to trigger this was that events were added to in-flight but offset not stored yet. Then a backtracking query emitted previous events that were rejected (throw exception) because seqNr wasn't the expected previous+1. Solution is to accept such events as duplicates when they are in-flight.
Fixes #245
> Allow envelope from backtracking as duplicate when in-flight, #245

- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
This reverts commit 2ea412112debf7bb6a1ef75a9ac68cfe1bbe0fec.
Since there was objections in https://github.com/akka/akka-persistence-r2dbc/pull/255#issuecomment-1173632942
Refs https://github.com/akka/akka-persistence-r2dbc/issues/253
> Revert "Save offsets in Batch without bind parameters, #253 (#255)"

- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/R2dbcDurableStateStore.scala
- core/src/test/scala/akka/persistence/r2dbc/TestActors.scala
- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateBySliceSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateStoreSpec.scala
- docs/src/main/paradox/query.md
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
* When deleting it will keep the record in the db, to keep track of latest revision number.
* Kept hard delete for revision=0 parameter.
* Emits DeletedDurableState in eventsBySlices query.
Fixes #276
> Implement Delete effect for DurableState, #276

- .github/workflows/fossa.yml
The Fossa CLI installation was outdated.
Changed to `coursier/setup-action` for the JDK and sbt installation.
References https://github.com/akka/akka-projection/pull/730
> chore: modern Fossa workflow

- build.sbt
Wrong base_url
(cherry picked from commit fb794b0d1ba6950304c11b352094a348656934a0)
Note: api docs were missing when releasing 1.0.0, but I have published them now.
> apidoc base_url

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
* With pub-sub enabled there are latency spikes when the db queries are running, especially the backtracking queries.
* Seems to help with mergePrioritized
* Also limited number of backtracking queries that will be run before mixing with ordinary query, for better fairness
> Reduce periodic latency spikes

- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateBySliceSpec.scala
It might take a while until we update to Akka 2.8.
Refs #289
> Workaround for failing DurableStateBySliceSpec, #289

- .github/workflows/fossa.yml
Fossa runs `sbt makePom` internally and needs more git history to make MiMa find the latest version.
> ci: check out full history for Fossa analyze

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/InstantFactory.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/R2dbcJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/BySliceQueryBucketsSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePubSubSpec.scala
- projection/src/test/resources/logback-test.xml
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreStateSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/TestClock.scala
* Truncate timestamps to microseconds because Postgres timestamps has the resolution of microseconds but some OS/JDK (Linux/JDK17) has Instant resolution of nanoseconds.
* This could have been a problem when sending the events directly vs reading through the db.
* Change TestClock to use microseconds or milliseconds and use it from tests instead of Instant.now().
* Some tests that are not using the timestamp offset must still use millisecond resolution.
References #321
> fix: Use explicit microsecond timestamp resolution, #321

- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
* and not call nanoTime
References #327
> fix: log-db-calls-exceeding=off  should  disable logging, #327

- .github/workflows/publish.yml
* because then it will bump the version and not match the tag
@ennru This can be a problem in all repositories where this was changed.
> build: don't copy jvmopts in publish workflow

- core/src/main/scala/akka/persistence/r2dbc/internal/EnvelopeOrigin.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/PubSub.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePubSubSpec.scala
- project/Dependencies.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
`R2dbcOffsetStore` is supposed to throw exception if a backtracking even is out of sync, but for events from the tail query and pubsub it should return false so that they are tried again when backtracking event arrives. The problem is for filtered events. We can't see if the filtered event is from backtracking or not. Looks like they are always from backtracking.
Filtered events are represented with `eventOption = None, eventMetadata = Some(NotUsed)`.
We need a way to see if the filtered event is from backtracking. That should still result in a hard error.
References #343
TODO:
> fix: Filtered event looks like backtracking event, #343

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePubSubSpec.scala
* because if consumer stores offset from PubSub event that is further ahead than than the backtracking window a subsequent restart of the consumer will not read the possibly missing events from backtracking
> fix: PubSub events shouldn't be too far ahead

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/EnvelopeOrigin.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePerfSpec.scala
https://github.com/akka/akka-persistence-r2dbc/pull/300 added some fairness to switch from backtracking earlier.
That is reverted in https://github.com/akka/akka-persistence-r2dbc/pull/345
This PR solves the original issue in a better way. Instead of only having a time based switch (half backtracking window) it is now also switching to backtracking if many events have been received by the ordinary queries.
> perf: Avoid too large bursts of backtracking events

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/AdditionalColumnFactory.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/ChangeHandlerFactory.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
- core/src/main/scala/akka/persistence/r2dbc/session/javadsl/R2dbcSession.scala
- core/src/main/scala/akka/persistence/r2dbc/session/scaladsl/R2dbcSession.scala
- core/src/main/scala/akka/persistence/r2dbc/state/ChangeHandlerException.scala
- core/src/main/scala/akka/persistence/r2dbc/state/javadsl/AdditionalColumn.scala
- core/src/main/scala/akka/persistence/r2dbc/state/javadsl/ChangeHandler.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/AdditionalColumn.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/ChangeHandler.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/R2dbcDurableStateStore.scala
- core/src/test/java/akka/persistence/r2dbc/state/JavadslChangeHandler.java
- core/src/test/java/akka/persistence/r2dbc/state/JavadslColumn.java
- core/src/test/scala/akka/persistence/r2dbc/state/CurrentPersistenceIdsQuerySpec.scala
- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateStoreAdditionalColumnSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateStoreChangeHandlerSpec.scala
- docs/src/main/paradox/durable-state-store.md
- docs/src/main/paradox/projection.md
- docs/src/test/java/jdocs/home/state/BlogPost.java
- docs/src/test/java/jdocs/home/state/BlogPostCounts.java
- docs/src/test/java/jdocs/home/state/BlogPostQuery.java
- docs/src/test/java/jdocs/home/state/BlogPostTitleColumn.java
- docs/src/test/scala/docs/home/state/BlogPost.scala
- docs/src/test/scala/docs/home/state/BlogPostCounts.scala
- docs/src/test/scala/docs/home/state/BlogPostQuery.scala
- docs/src/test/scala/docs/home/state/BlogPostTitleColumn.scala
* for storing query representation from the write side in same transaction as the upsert
* support for additional columns in the durable_state table, for secondary indexes
* support for any additional processing for storing more complex
representations, such as in a secondary table, still in same transaction
When reviewing it might be easier to look at the individual commits, which adds one feature at a time.
References #90
TODO:
> feat: Support for storing query representation for durable state from the write side

- project/Dependencies.scala
Netty bump got merged and released upstream:
https://github.com/pgjdbc/r2dbc-postgresql/releases/tag/v1.0.1.RELEASE
Reverts
- #355
> bump: r2dbc-postgresql 1.0.1 (was 1.0.0)

- core/src/main/scala/akka/persistence/r2dbc/query/R2dbcReadJournalProvider.scala
Not a huge thing, but the Scala 3 work made these lazy while they were previously eagerly constructed with the provider, so changing it back so it works exactly like before.
> chore: Un-lazy the read journal providers

- core/src/main/scala/akka/persistence/r2dbc/internal/Sql.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/SqlSpec.scala
A double question mark `??` is used to provide a single question mark `?` to the output statement.
> Allow escaping of literal `?` in SQL statements

- .github/workflows/nightly.yml
Refs #368
#367 changed the scala 3 postgres nightly from `core/test` to `test`, which fails to compile. Change this back again.
> ci: restore scala 3 postgres nightly only running core/test

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/PayloadCodec.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/SnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/test/scala/akka/persistence/r2dbc/journal/PersistTimestampSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- ddl-scripts/create_tables_postgres_jsonb.sql
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
* All test data has been changed to be valid json (test inheriting from plugin tck classes which uses non json compatible payloads have been marked as ignored for now) 
* New settings added:
```
akka.persistence.r2dbc.journal.payload-column-type = "json" | "jsonb" | "bytea"
akka.persistence.r2dbc.snapshot.payload-column-type = "json" | "jsonb" | "bytea"
akka.persistence.r2dbc.state.payload-column-type = "json" | "jsonb" | "bytea"
```
* Create the database using the jsonb ddl script variant at:
```
ddl-scripts/create_tables_postgres_jsonb.sql
```
* Run tests with:
```
sbt -Dakka.persistence.r2dbc.journal.payload-column-type=jsonb  -Dakka.persistence.r2dbc.snapshot.payload-column-type=jsonb  -Dakka.persistence.r2dbc.state.payload-column-type=jsonb test
```
> Add support for using json/jsonb as column type for payloads (pg only)

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/ConnectionFactoryProvider.scala
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
Allow client certificates for SSL connections to be configured. Just passing more of the connection options.
> feat: support client certificates in SSL connections

- core/src/main/scala/akka/persistence/r2dbc/query/javadsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsByPersistenceIdSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsByPersistenceIdStartingFromSnapshotSpec.scala
- docs/src/main/paradox/query.md
* EventsByPersistenceIdStartingFromSnapshotQuery
* CurrentEventsByPersistenceIdStartingFromSnapshotQuery
On top of https://github.com/akka/akka-persistence-r2dbc/pull/410
Waiting for Akka release that includes https://github.com/akka/akka/pull/31980
> feat: Snapshot as starting point for eventsByPersistenceId

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/ConnectionFactoryProvider.scala
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/ConnectionFactorySettings.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresJournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresSnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/session/scaladsl/R2dbcSession.scala
- core/src/test/scala/akka/persistence/r2dbc/TestDbLifecycle.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/R2dbcExecutorSpec.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationTool.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationToolDao.scala
- project/Dependencies.scala
* The underlying connection is closed if timeout exceeded, and connection will not be reused by the pool.
* This timeout is needed to handle some failure scenarios, when the database server is terminated in a non graceful way and there is a load balancer in front. The client connection and current execution in progress would not be completed without this timeout, resulting in a "connection leak".
* Also adding config for server side statement timeout
* forward port, cherry picked from commit 6e8b236583fc541d8e89fa53cb23a6291ebaeb9a
Forward port of https://github.com/akka/akka-persistence-r2dbc/pull/419
> fix: Close connection if execution takes too long (fw port)

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/ConnectionFactoryProvider.scala
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/session/scaladsl/R2dbcSession.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/SnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/test/scala/akka/persistence/r2dbc/TestDbLifecycle.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/R2dbcExecutorSpec.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationTool.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationToolDao.scala
* The current transaction will be rolled back and connection closed if exceeded.
* This timeout is needed to handle some failure scenarios, when the database server is terminated in a non graceful way and there is a load balancer in front. The client connection and current execution in progress would not be completed without this timeout, resulting in a "connection leak".
I have tried this by simulating execution that takes longer than the timeout with `pg_sleep`, but I haven't included tests yet. Will make a new test for this.
> fix: Close connection if execution takes too long

- project/Dependencies.scala
https://github.com/pgjdbc/r2dbc-postgresql/releases/tag/v1.0.2.RELEASE
Mainly for fixing reconnection issues.
Backport for 1.1.2 as well?
> bump: r2dbc-postgresql 1.0.2 (was 1.0.1)

- .github/workflows/build-test.yml
- .github/workflows/nightly.yml
- CONTRIBUTING.md
- docker/docker-compose-postgres.yml
- docs/src/main/paradox/getting-started.md
> chore: add docker-compose healthcheck for postgres

- core/src/main/scala/akka/persistence/r2dbc/ConnectionFactoryProvider.scala
* for the new closeCallsExceeding paramater in R2dbcExecutor, needed from R2dbcProjection
> chore: ConnectionPoolSettings from ConnectionFactoryProvider

- core/src/main/mima-filters/1.1.1.backwards.excludes/internal.BySliceQuery.QueryState.excludes
- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
Backtracking queries can stop too early. This can create a gap between the normal db queries and the backtracking queries that's longer than the backtracking window, and if a projection instance is then restarted, there are events that are completely missed, or rejected because of earlier missed events.
The switch-from-backtracking check compares how many rows were returned by the past query to the buffer size - 1. The 1 is for the event at the initial timestamp, which has already been seen by the previous query and will be filtered from the result. If there are events that share timestamps (because they were emitted together), then there can be multiple events filtered out of the result set. In this case, it will switch from backtracking mode before catching up, and while it can still …
> fix: backtracking queries and filtered events

- core/src/main/mima-filters/1.1.1.backwards.excludes/internal.BySliceQuery.QueryState.excludes
- core/src/main/mima-filters/1.2.0-M4.backwards.excludes/internal.BySliceQuery.QueryState.excludes
- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
Forward port of https://github.com/akka/akka-persistence-r2dbc/pull/445
* update: add mima filters for QueryState
(cherry picked from commit 6c465cbccd864196c20ab50626c9300d6d74c6fb)
> fix: backtracking queries and filtered events (#445)

- core/src/main/scala/akka/persistence/r2dbc/journal/R2dbcJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/scala/akka/persistence/r2dbc/journal/PersistSerializedEventSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/journal/PersistTagsSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePubSubSpec.scala
- project/Dependencies.scala
See https://github.com/akka/akka/pull/32068 and https://github.com/akka/akka-projection/pull/959
> perf: Avoid event serialization roundtrip

- .github/workflows/nightly.yml
- project/Dependencies.scala
See https://github.com/akka/akka/pull/32125
> chore: Drop Scala 2.12

- core/src/main/mima-filters/1.2.0-M5.backwards.excludes/isPayloadDefined.excludes
- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/SnapshotDao.scala
* NullPointerException in isPayloadDefined
* regression when adding the starting from snapshots, i.e. this bug was not released in any final version (but in milestones)
* for durable state we use null payload as the backtracking marker in the row, becuse we also have the deleted case, ugly but that goes all the way to Akka's UpdatedDurableState
> fix: Envelope source is different for durable state

- project/Dependencies.scala
* Override reactor-netty-core from r2dbc-postgresql to include Netty 4.1.100, fixing CVE-2023-4586
> bump: reactor-netty-core 1.1.12

- build.sbt
As it turns out, sbt translates the project name into the pom identifier `artifactId`. This PR changes the project name for the documentation sbt project so that sbt creates unique pom identifiers for the core project and the docs project. This helps other tools to consume the pom files correctly.
> chore: change docs project name to disambiguate from  in pom files

- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDurableStateDao.scala
- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateStoreChangeHandlerSpec.scala
* the check and throw is outside the transaction
* I don't see the need for rollback, though
> fix: Don't call change handler if optimistic lock fails

- core/src/test/scala/akka/persistence/r2dbc/query/CurrentPersistenceIdsQuerySpec.scala
Before this pr, this test failed when running `sbt 'testOnly *.CurrentPersistenceIdsQuerySpec'` as it causes a false negative for wrongly sorted set cased by single / multi digits edge case for generated ids.
> fix: avoid failing when running with testOnly mode

- core/src/main/scala/akka/persistence/r2dbc/cleanup/scaladsl/DurableStateCleanup.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/PubSub.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2Dialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresJournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/YugabyteDialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/YugabyteDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/javadsl/R2dbcDurableStateStore.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/R2dbcDurableStateStore.scala
- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateUpdateWithChangeEventStoreSpec.scala
- project/Dependencies.scala
Early draft to show where the idea is going.
TODO:
> feat: Write change event of DurableState to event journal

- core/src/main/scala/akka/persistence/r2dbc/cleanup/javadsl/EventSourcedCleanup.scala
- core/src/main/scala/akka/persistence/r2dbc/cleanup/scaladsl/EventSourcedCleanup.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresJournalDao.scala
- core/src/test/scala/akka/persistence/r2dbc/cleanup/scaladsl/EventSourcedCleanupSpec.scala
- docs/src/main/paradox/cleanup.md
* This can be useful for `DurableStateBehavior` with change events, where the events are only used for the Projections and not for the recovery of the `DurableStateBehavior` state. The timestamp may correspond to the the offset timestamp of the Projections, if events are not needed after all Projections have processed them.
> feat: Cleanup events by time

- core/src/main/scala/akka/persistence/r2dbc/cleanup/javadsl/EventSourcedCleanup.scala
- core/src/main/scala/akka/persistence/r2dbc/cleanup/scaladsl/EventSourcedCleanup.scala
Small follow-up to #495, fix `the the` typo.
> docs: fix double `the` in cleanup api docs

- .github/workflows/nightly.yml
Nightly jobs like [this](https://github.com/akka/akka-persistence-r2dbc/actions/runs/7455770340/job/20285358045) seem to crash without returning an error code properly.
> fix: make nightlies not fail silently

- core/src/test/scala/akka/persistence/r2dbc/TestActors.scala
- docs/src/main/paradox/migration.md
- migration-tests/src/test/scala/akka/persistence/r2dbc/migration/MigrationToolSpec.scala
- migration/src/main/resources/reference.conf
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationTool.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationToolDao.scala
* adding Durable State to the MigrationTool
* currently doesn't support retrieval of all persistenceIds because the jdbc plugin doesn't implement PersistenceIdsQuery, and jdbc plugin is currently the only other know plugin for durable state
References #504
> feat: Migration of Durable State, #504

- docs/src/main/paradox/migration.md
A `@@@ note` does not need to be closed like it was before this PR, and for me it even breaks the rendering.
> docs: fix note rendering in Running section

- core/src/main/scala/akka/persistence/r2dbc/cleanup/scaladsl/DurableStateCleanup.scala
- core/src/main/scala/akka/persistence/r2dbc/cleanup/scaladsl/EventSourcedCleanup.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/Dialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2Dialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2SnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresJournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresSnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/YugabyteDialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/YugabyteDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/YugabyteQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/YugabyteSnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerDialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerJournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerSnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/R2dbcJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/R2dbcSnapshotStore.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/R2dbcDurableStateStore.scala
- core/src/test/scala/akka/persistence/r2dbc/TestDbLifecycle.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationTool.scala
* H2 requires blocking dispatcher, which was lost in the data partitions refactoring #508 
* reduce number of parameters of dao creation since everything needed is included in R2dbcExecutorProvider
> chore: Dao ExecutionContext in R2dbcExecutorProvider

- build.sbt
- docs/src/main/paradox/migration.md
- migration-tests/src/test/resources/application-sqlserver-example.conf
- migration-tests/src/test/resources/application-sqlserver.conf
- migration-tests/src/test/resources/logback-test.xml
- migration-tests/src/test/scala/akka/persistence/r2dbc/migration/MigrationToolSpec.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationTool.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationToolDao.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/SqlServerMigrationToolDao.scala
- project/Dependencies.scala
Fixes https://github.com/akka/akka-persistence-r2dbc/issues/509
> feat: migration for sqlserver

- .github/workflows/build-test.yml
- .github/workflows/fossa.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
* Node.js 16 actions are deprecated
* actions/checkout, coursier/cache-action, coursier/setup-action
* using same versions as in akka-projection
> build: Update actions due to Node.js 16 deprecation

- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2Dialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2SnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresSnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerSnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/session/scaladsl/R2dbcSession.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/R2dbcDurableStateStore.scala
- core/src/test/scala/akka/persistence/r2dbc/PayloadSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/R2dbcSettingsSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/TestDbLifecycle.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/H2AdditionalInitForSchemaSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/state/CurrentPersistenceIdsQuerySpec.scala
- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateBySliceSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateStoreAdditionalColumnSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateStoreChangeHandlerSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateUpdateWithChangeEventStoreSpec.scala
- ddl-scripts/create_tables_postgres_0-1.sql
- ddl-scripts/create_tables_postgres_2-3.sql
On top of #508 , and not complete yet
> feat: Data partitions for snapshot and durable state

- core/src/main/scala/akka/persistence/r2dbc/internal/Sql.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2SnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresJournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresSnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerJournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerSnapshotDao.scala
- migration-tests/src/test/scala/akka/persistence/r2dbc/migration/MigrationToolSpec.scala
* avoid string concatenation and allocations
* since they are  now created each time its used due to the data partitions by slice
@johanandren can you sanity check this before I continue?
> perf: Cache sql construction

- docs/src/main/paradox/getting-started.md
Was missed in https://github.com/akka/akka-persistence-r2dbc/pull/505.
> docs: add missing getting-started docs for SQLServer

- .github/workflows/native-image-tests.yml
- core/src/main/resources/META-INF/native-image/io.netty/netty-handler/native-image.properties
- core/src/main/resources/META-INF/native-image/org.postgresql/r2dbc-postgresql/reflect-config.json
- native-image-tests/src/main/resources/logback.xml
References #548 
r2dbc postgres bump transitively bumped Netty which broke native-image, also found some unsupported reflection inspection when logging native image run at debug which was fixed.
> chore: Native-image support with r2dbc-postgres 1.0.5.RELEASE

- core/src/main/scala/akka/persistence/r2dbc/internal/DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDurableStateDao.scala
- migration-tests/src/test/resources/application-postgres.conf
- migration-tests/src/test/scala/akka/persistence/r2dbc/migration/MigrationChangeHandler.scala
- migration-tests/src/test/scala/akka/persistence/r2dbc/migration/MigrationTestColumn.scala
- migration-tests/src/test/scala/akka/persistence/r2dbc/migration/MigrationToolSpec.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/DurableStateMigrationToolDao.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationTool.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationToolDao.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/SqlServerMigrationToolDao.scala
Reopening of #554, follow up to https://github.com/akka/akka-persistence-r2dbc/pull/560
Open tasks:
> fix: insert instead of update new state with updated revision during migration

- docs/src/main/paradox/data-partition.md
- docs/src/main/paradox/index.md
Trigged by some feedback I looked closer at what others say regarding sharding vs partitioning.Seems like sharding is mostly used for horizontal partitioning to distribute the data across multiple servers. While partitioning is a more generic term it mostly refers to splitting up large tables into smaller tables, but still in one database instance (*vertical scaling").
Our primary goal is horizontal scaling so we should highlight database sharding.
That said, the implementation splits the data into multiple tables (partitioning), which can then optionally be located on different database instances (sharding). The documentation still uses data partition and that it corresponds to a table. I think that is fine, but let me know if it's confusing.
> doc: Sharding vs partitioning

- migration-tests/src/test/scala/akka/persistence/r2dbc/migration/MigrationChangeHandler.scala
- migration-tests/src/test/scala/akka/persistence/r2dbc/migration/MigrationToolSpec.scala
> chore: Fix Scala 3 migration tests compilation

- core/src/test/scala/akka/persistence/r2dbc/snapshot/R2dbcSnapshotStoreSpec.scala
- docs/src/main/paradox/snapshots.md
Noticed when reusing this test elsewhere: sequence number was incorrect, so it wasn't actually deleting a snapshot. Test still passed as successful if there's no matching snapshot. Rather than just set to the correct sequence number (15) also future proof by checking what it is before delete.
Also fix a typo in the snapshot store docs.
> test: correct sequence number for delete single snapshot test

- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2Dialect.scala
- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_postgres_0-1.sql
- ddl-scripts/create_tables_postgres_2-3.sql
- ddl-scripts/create_tables_postgres_jsonb.sql
- ddl-scripts/create_tables_sqlserver.sql
- ddl-scripts/create_tables_yugabyte.sql
- docs/src/main/paradox/migration-guide.md
Mentioned in https://github.com/akka/akka-persistence-r2dbc/issues/558#issuecomment-2071979388
> chore: drop revision from Durable State by slice index and migration docs

- build.sbt
- core/src/main/scala/akka/persistence/r2dbc/internal/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/R2dbcJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- native-image-tests/build.sbt
- project/Dependencies.scala
* AsyncReplay added in Akka https://github.com/akka/akka/pull/32434
Requires a new version of Akka before merging
> perf: Avoid asyncReadHighestSequenceNr query

- core/src/test/scala/akka/persistence/r2dbc/cleanup/scaladsl/EventSourcedCleanupSpec.scala
* would fail when the two random pids have the same slice
Refs https://github.com/akka/akka-persistence-r2dbc/issues/549
Refs https://github.com/akka/akka-persistence-r2dbc/issues/547
Refs https://github.com/akka/akka-persistence-r2dbc/issues/530
> test: Harden EventSourcedCleanupSpec, #549

- .github/workflows/build-test.yml
- core/src/main/mima-filters/1.2.4.backwards.excludes/rows-by-slices.excludes
- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresSnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerQueryDao.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
- docker/docker-compose-sqlserver.yml
We've seen a case where more than 1000 events were persisted together (so have the same timestamp), and more than the default query buffer size, and then queries will be stuck on the same timestamp and never make further progress.
Since events are ordered by timestamp and sequence number, update the queries to also filter by the highest seen seq number for the latest timestamp (only for events with the same timestamp as this starting timestamp). Fixes the case where all the events are for the same persistence id. Queries will still duplicate on the events with both the same timestamp and seq number (different persistence ids), to handle events across the buffer limit. The very edge case of more events than the buffer size all with the same timestamp and the same seq number (from different …
> fix: stuck queries when too many events with same timestamp

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/ConnectionFactoryProvider.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/ConnectionFactorySettings.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/Dialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2Dialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/YugabyteDialect.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerDialect.scala
- core/src/test/scala/akka/persistence/r2dbc/R2dbcSettingsSpec.scala
* Possibility to amend the ConnectionFactoryOptions
> feat: Programatic connection factory options

- README.md
- build.sbt
- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/query/javadsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- docs/release-train-issue-template.md
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationTool.scala
References
- https://github.com/akka/akka/pull/32518
> docs: revise URL structure (libraries)

- .github/workflows/link-validator.yml
- .github/workflows/publish.yml
- build.sbt
- project/Dependencies.scala
- project/project-info.conf
- scripts/link-validator.conf
Running the link validator showed broken links since the JPMS structure got introduced.
Interestingly enough, I had to use links without `java.base` on this repo, which is different to what Akka Management required. Didn't want to spend time digging why.
References
- https://github.com/akka/akka-management/pull/1319/commits/f85e9f9f0c107ec7bc713a2201157aabd18adcae
> docs: configure links in ScalaDoc; run link validator

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePerfSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePubSubBacktrackingSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceStartingFromSnapshotSpec.scala
Filter heartbeats once received by the skip pubsub if too far ahead check.
Remove some extra filtering from tests again, which should fail if heartbeats are emitted.
Have left the heartbeat creation as is, including the search for appropriate persistence id, but heartbeats could also be simpler dummy envelopes now that they're not going further and to the offset store.
> fix: filter heartbeats early in pubsub merge

- scripts/link-validator.conf
PRs have been failing link validation, on linking to `String$`. There's already an ignore for this, but docs and link validator are building with Java 17.
> fix: link validator ignore for String$

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/R2dbcDurableStateStore.scala
Corresponding to https://github.com/akka/akka-persistence-dynamodb/pull/112
> chore: More information in query log prefix

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
Corresponding to https://github.com/akka/akka-persistence-dynamodb/pull/109
> fix: only initial backtracking up to start offset when far behind

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
Port of https://github.com/akka/akka-persistence-dynamodb/pull/104
> fix: don't trigger heartbeats from idle backtracking

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
Now that we disable backtracking when far behind, this old debug log is not so useful — will log every offset in catch up mode. Removing it. Alternative would be to explicitly track when in catch up mode with disabled backtracking in the state, so we only log this when backtracking is enabled.
> chore: remove obsolete outside backtracking debug log

- core/src/main/mima-filters/1.3.0.backwards.excludes/buckets.excludes
- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/BySliceQueryBucketsSpec.scala
* it was using state.latestBacktracking.timestamp as fromTimestamp for the bucket count query, which will not progress when backtracking is disabled
* instead, use (almost) last bucket time from previous query
> fix: Bucket count query start timestamp

- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
Refs https://github.com/akka/akka-persistence-r2dbc/issues/637
Seems to work as expected.
> test: Small addition to disabled backtracking test

- core/src/main/mima-filters/1.3.1.backwards.excludes/buckets.excludes
- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresSnapshotDao.scala
- core/src/test/scala/akka/persistence/r2dbc/TestDbLifecycle.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/BySliceQueryBucketsSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/BucketCountSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
* the bucket queries continues from the end of the previous
* the limit of 10000 times 10 seconds is around 28 hours
* meaning that if there were no new events for 28 hours the queries will not progress since it will not find any more
* solution here is to append empty bucket at the end in that case
Follow up on https://github.com/akka/akka-persistence-r2dbc/pull/641
> fix: Progress bucket count query if empty

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/test/scala/akka/persistence/r2dbc/query/BucketCountSpec.scala
Fixes https://github.com/akka/akka-persistence-r2dbc/issues/649
> chore: Rounding of epoch seconds

- .scala-steward.conf
- native-image-tests/build.sbt
- project/Dependencies.scala
This reverts commit 080467538248db24823d3d5745c5f2e976422717.
Reverts https://github.com/akka/akka-persistence-r2dbc/pull/648 for now because it enforces updates to all downstream usage, including end users. We'll probably have to bump Scala versions in a more coordinated way, from the ground up.
```
scalaInstance) expected `scalaVersion` to be "2.13.16" or later,
[error] but found "2.13.15"; upgrade scalaVersion to fix the build.
[error]
[error] to support backwards-only binary compatibility (SIP-51),
[error] the Scala 2.13 compiler cannot be older than scala-library on the
[error] dependency classpath.
```
> Revert "bump: scala-library 2.13.16 (was 2.13.15) (#648)"

- core/src/main/scala/akka/persistence/r2dbc/internal/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/postgres/PostgresQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/R2dbcJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/R2dbcSnapshotStore.scala
- core/src/test/scala/akka/persistence/r2dbc/TestActors.scala
- core/src/test/scala/akka/persistence/r2dbc/journal/R2dbcJournalSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsByPersistenceIdSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/LastEventByPersistenceIdSpec.scala
- project/Dependencies.scala
Implementation of https://github.com/akka/akka/pull/32629
* bump: Akka core 2.10.1
> feat: Recovery based on only the last event

- core/src/test/scala/akka/persistence/r2dbc/RetryableTests.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
Refs #681
Extend cache TTL to give more time fore cache results. Mark test as retryable.
Will trigger multiple test runs.
> test: update flaky LatestEventTimestampQuery cache test
