akka/akka-persistence-r2dbc

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcSerializer.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider2.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/SpannerSerializerSpec.scala
- ddl-scripts/create_tables_postgres.sql
- project/Dependencies.scala
and Serializer for TimestampOffset
> EventSourcedProvider for eventsBySlices projection

- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
* I don't think it was wrong, but maybe somewhat confusing
* It's documented as:
Binding also allowed positional index (zero-based) references.
The parameter index is derived from the parameter discovery order when parsing the query.
> Query params in same order as param index

- build.sbt
- project/Dependencies.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/main/scala/akka/projection/r2dbc/scaladsl/R2dbcProjection.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
> Filter duplicates for async and flow projections, #35

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
> inflight cache accept event after retry

- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/test/scala/akka/persistence/r2dbc/journal/R2dbcJournalSpec.scala
> Metadata for replicated event sourcing, #85

- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_yugabyte.sql
- projection/src/test/scala/akka/projection/r2dbc/R2dbcProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
* previous problem was because the wrong connection management
> Create the test table from the tests

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/state/scaladsl/DurableStateSourceProvider2.scala
- projection/src/test/scala/akka/projection/r2dbc/DurableStateEndToEndSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedChaosSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/TestDbLifecycle.scala
> DurableState Projection, #79

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
> Fix wrong logic in isAccepted

- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/scala/akka/persistence/r2dbc/TestActors.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsByPersistenceIdSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
* also verify that metadata from replicated event sourcing is included
in eventsByPersistenceId and eventsBySlices
Fixes #80
> eventsByPersistenceId query, #80

- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_yugabyte.sql
- projection/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider2.scala
- projection/src/main/scala/akka/projection/eventsourced/scaladsl/TimestampOffsetBySlicesSourceProvider.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/main/scala/akka/projection/r2dbc/scaladsl/R2dbcProjection.scala
- projection/src/main/scala/akka/projection/state/scaladsl/DurableStateSourceProvider2.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
Draft because on top of other PRs, but otherwise ready for review.
Fixes #57
> Include slice in offset table, #57

- projection/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
Similar to what is used in ChaosSpec.
To be able to diagnose failures like in https://github.com/akka/akka-persistence-r2dbc/issues/109
> Better error reporting in EndToEndSpec

- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePerfSpec.scala
* failed a few times in CI with Yugabyte, and also noticed
that locally
> Reduce EventsBySlicePerfSpec

- core/src/main/scala/akka/persistence/r2dbc/snapshot/R2dbcSnapshotStore.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/SnapshotDao.scala
- core/src/test/scala/akka/persistence/r2dbc/TestConfig.scala
- core/src/test/scala/akka/persistence/r2dbc/TestDbLifecycle.scala
- core/src/test/scala/akka/persistence/r2dbc/snapshot/R2dbcSnapshotStoreSpec.scala
- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_yugabyte.sql
- ddl-scripts/drop_tables_postgres.sql
> feat: Snapshot store added 

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/ContinuousQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/ContinuousQuerySpec.scala
> Adjust live query refresh rate based on previous result, #28

- .github/workflows/publish.yml
- project/plugins.sbt
* and publish snapshots from main commits
> Latest sbt-ci-release

- .github/workflows/build-test.yml
- .github/workflows/publish.yml
```
Error loading key "/tmp/id_rsa": invalid format
```
> Disable doc publish since it fails

- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
* because they may be logged (and it wasn't consistent in all places)
> Remove linebreaks in sql

- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/R2dbcJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/R2dbcDurableStateStore.scala
- core/src/test/scala/akka/persistence/r2dbc/journal/PersistTimestampSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_yugabyte.sql
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
* better to use the db_timestamp for this
> Remove unecessary write_timestamp column

- core/src/main/scala/akka/persistence/query/javadsl/CurrentDurableStatePersistenceIdsQuery.scala
- core/src/main/scala/akka/persistence/query/javadsl/CurrentEventsBySliceQuery.scala
- core/src/main/scala/akka/persistence/query/javadsl/DurableStateStoreBySliceQuery.scala
- core/src/main/scala/akka/persistence/query/javadsl/EventsBySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/javadsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/state/javadsl/R2dbcDurableStateStore.scala
javadsl for projection is not done yet
Refs #83
> javadsl for the queries, #83

- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/R2dbcJournal.scala
> Possibility to preserve event timestamp when writing from MigrationTool

- CONTRIBUTING.md
- core/src/main/scala/akka/persistence/query/scaladsl/EventTimestampQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/R2dbcJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/R2dbcSnapshotStore.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/SnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/test/scala/akka/persistence/r2dbc/journal/PersistTimestampSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_yugabyte.sql
- design-notes.md
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationTool.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationToolDao.scala
- projection/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider2.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
* takes up too much screen estate for `select *` in psql
> Rename sequence_number column to seq_nr

- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
> Use batch statements

- core/src/main/scala/akka/persistence/query/scaladsl/EventsBySliceQuery.scala
- core/src/main/scala/akka/persistence/query/scaladsl/LoadEventQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
- ddl-scripts/create_tables_yugabyte.sql
- projection/src/main/scala/akka/projection/eventsourced/scaladsl/EventSourcedProvider2.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/main/scala/akka/projection/r2dbc/scaladsl/R2dbcProjection.scala
- projection/src/main/scala/akka/projection/state/scaladsl/DurableStateSourceProvider2.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
> Lazy loading of events/state for backtracking queries, #76

- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
> minor improvements on withConnection method usage

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/test/scala/akka/persistence/r2dbc/state/DurableStateStoreSpec.scala
* adding two tuning parameters because I would like to be easily
test the performance impact of these
* might be removed again, depending on result
> Tuning parameters

- build.sbt
- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/state/javadsl/R2dbcDurableStateStore.scala
- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_yugabyte.sql
- design-notes.md
- docs/src/main/paradox/connection-config.md
- docs/src/main/paradox/contributing.md
- docs/src/main/paradox/durable-state-store.md
- docs/src/main/paradox/getting-started.md
- docs/src/main/paradox/index.md
- docs/src/main/paradox/journal.md
- docs/src/main/paradox/migration.md
- docs/src/main/paradox/overview.md
- docs/src/main/paradox/query.md
- docs/src/main/paradox/snapshots.md
- docs/src/test/java/jdocs/home/query/QueryDocCompileOnly.java
- docs/src/test/resources/application-postgres.conf
- docs/src/test/resources/application-yugabyte.conf
- docs/src/test/scala/docs/home/query/QueryDocCompileOnly.scala
- project/Dependencies.scala
Doesn't include docs for Projections yet. I'll add that in a separate PR.
References #89
> Reference documentation, #89

- projection/src/test/scala/akka/projection/r2dbc/R2dbcProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
Follow up on https://github.com/akka/akka-persistence-r2dbc/pull/148
Some more tests that may have similar issues with the async saving of the offset.
References #147
> More hardening of ProjectionSpec, #147

- build.sbt
- docs/src/main/paradox/getting-started.md
- docs/src/main/paradox/index.md
- docs/src/main/paradox/overview.md
- docs/src/main/paradox/projection.md
- docs/src/main/paradox/query.md
- docs/src/test/scala/docs/home/projection/R2dbcProjectionDocExample.scala
- project/Dependencies.scala
- project/project-info.conf
- projection/src/main/resources/reference.conf
> Reference documentation for Projections, #89

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
* to get insight into if we need further improvement
> Error when event from backtracking is rejected

- core/src/test/resources/logback-test.xml
- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_yugabyte.sql
- projection/src/main/resources/reference.conf
- projection/src/main/scala/akka/projection/r2dbc/R2dbcProjectionSettings.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/TestDbLifecycle.scala
* and implement `clearOffset` fully
> Make primitive offset table optional

- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/SnapshotDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_yugabyte.sql
* see discussion and testing in issue #175
Fixes #175
cc @jrudolph
> Remove slice from primary key, #175

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
* small resource usage optimization
> Avoid repeatly trying to delete offsets when idle

- ddl-scripts/create_tables_yugabyte.sql
Tested and with this it distributes the load over all (3) tservers.
Fixes #174
> Split slice index, #174

- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
* simplifies the code
* no measurable difference in performance, tried with
R2dbcJournalPerfSpec and R2dbcJournalPerfManyActorsSpec and local Postgres
> Use Mono for Publisher to Future conversion

- core/src/main/scala/akka/persistence/r2dbc/internal/PubSub.scala
https://github.com/akka/akka-persistence-r2dbc/runs/4962877931?check_suite_focus=true#step:4:47
> URLEncoder.encode for jdk 8

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
It wasn't fully implemented for timestamp offsets.
> Projection magement clear/set offset

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
* too verbose at info when pub-sub is enabled
> Adjust log level for 'Rejecting unexpected sequence number'

- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
@johanandren I noticed you could benefit from this, and we should probably use it in other places where we create table and index
> add executeDdls for several ddl statements in same tx

- docker/docker-compose-yugabyte.yml
https://docs.yugabyte.com/latest/releases/whats-new/stable-release/#v2.12.1.0
> Update to Yugabyte 2.12.1

- docker/docker-compose-yugabyte.yml
Didn't change both versions in #213
> Update to Yugabyte 2.12.1, both servers

- docker/docker-compose-yugabyte.yml
https://docs.yugabyte.com/latest/releases/release-notes/v2.12/#v2.12.2.0
> Update to Yugabyte 2.12.2.0-b58

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/test/scala/akka/persistence/r2dbc/TestActors.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/BySliceQueryBucketsSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/state/TestDataGenerator.scala
Corresponding to https://github.com/akka/akka-persistence-r2dbc/pull/210 but for Durable State.
Fixes #212
> Upper bound on db_timestamp in changesBySlices query, #212

- core/src/main/scala/akka/persistence/r2dbc/query/R2dbcReadJournalProvider.scala
> Use same instance of the ReadJournal

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
* found this when replaying a projection from start
* it was very slow because the backtracking and normal queries switched back-n-forth
when replaying the old events, which is as expected, but that also added a
3 seconds delay each time when the backtracking query result was 0 rows
> No delay when switching from backtracking

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePubSubSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedPubSubSpec.scala
* best effort deduplication in eventsBySlices query when sending events over pubsub
> Deduplicate when using publish-events

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
> Use IN for Postgres in slice query, #249

- project/Dependencies.scala
* only needed for the tests of the migration tool
> Remove Postgres jdbc dependency

- .github/workflows/build-test.yml
- build.sbt
- core/src/main/scala/akka/persistence/r2dbc/ConnectionFactoryProvider.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/R2dbcExecutor.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/state/javadsl/R2dbcDurableStateStore.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/R2dbcDurableStateStore.scala
- core/src/test/scala/akka/persistence/r2dbc/TestActors.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- docs/src/main/paradox/getting-started.md
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationTool.scala
- migration/src/main/scala/akka/persistence/r2dbc/migration/MigrationToolDao.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/BySliceSourceProviderAdapter.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcProjectionImpl.scala
- projection/src/main/scala/akka/projection/r2dbc/javadsl/R2dbcSession.scala
- projection/src/test/scala/akka/projection/r2dbc/DurableStateEndToEndSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedChaosSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedPubSubSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetProjectionSpec.scala
Needed for bringing Akka Projection gRPC into Akka Projection.
> chore: Make it build with Scala 2.12

- docs/src/main/paradox/snapshots.md
> chore: Document only one entry per pid in snapshot store

- project/Dependencies.scala
- project/build.properties
> Scala 2.12.17 & 2.13.10

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/EWMA.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/PubSub.scala
- core/src/test/scala/akka/persistence/r2dbc/internal/EWMASpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceBacktrackingSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePubSubSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
- docs/src/main/paradox/projection.md
- docs/src/main/paradox/query.md
- project/Dependencies.scala
I'll try it out in a sample application for Projections over gRPC, but otherwise ready for review.
> Dynamically enable/disable publish-events

- .github/workflows/build-test.yml
- .github/workflows/fossa.yml
- .github/workflows/publish.yml
- .jvmopts-ci
References https://github.com/akka/akka/pull/31730
> ci: renovate GH workflows

- .github/workflows/build-test.yml
- .github/workflows/fossa.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
> ci: cross-test combinations in nightly tests

- projection/src/test/resources/logback-test.xml
Trying to find the cause of test failure https://github.com/akka/akka-persistence-r2dbc/issues/321
> tmp trace logging

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/R2dbcSettings.scala
- core/src/main/scala/akka/persistence/r2dbc/cleanup/javadsl/DurableStateCleanup.scala
- core/src/main/scala/akka/persistence/r2dbc/cleanup/javadsl/EventSourcedCleanup.scala
- core/src/main/scala/akka/persistence/r2dbc/cleanup/scaladsl/DurableStateCleanup.scala
- core/src/main/scala/akka/persistence/r2dbc/cleanup/scaladsl/EventSourcedCleanup.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/R2dbcJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/snapshot/SnapshotDao.scala
- core/src/test/scala/akka/persistence/r2dbc/TestActors.scala
- core/src/test/scala/akka/persistence/r2dbc/cleanup/scaladsl/DurableStateCleanupSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/cleanup/scaladsl/EventSourcedCleanupSpec.scala
- docs/src/main/paradox/cleanup.md
- docs/src/main/paradox/durable-state-store.md
- docs/src/main/paradox/index.md
- docs/src/main/paradox/journal.md
- docs/src/main/paradox/snapshots.md
- docs/src/test/java/jdocs/home/cleanup/CleanupDocExample.java
- docs/src/test/scala/docs/home/cleanup/CleanupDocExample.scala
* to support deletes of events and snapshots
TODO:
> feat: Cleanup tool

- core/src/main/resources/reference.conf
References https://github.com/akka/akka/pull/31784
> perf: only-one-snapshot config

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/internal/PubSub.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePubSubSpec.scala
- docs/src/main/paradox/query.md
> feat: Configuration of number of pub-sub topics, #252

- CONTRIBUTING.md
- core/src/main/scala/akka/persistence/r2dbc/query/javadsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/QueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/query/scaladsl/R2dbcReadJournal.scala
- core/src/main/scala/akka/persistence/r2dbc/state/javadsl/R2dbcDurableStateStore.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/R2dbcDurableStateStore.scala
- core/src/test/scala/akka/persistence/r2dbc/query/CurrentPersistenceIdsQuerySpec.scala
- core/src/test/scala/akka/persistence/r2dbc/state/CurrentPersistenceIdsQuerySpec.scala
References https://github.com/lightbend/kalix-proxy/issues/1824
> feat: currentPersistenceIds with entity type filtering

- project/Dependencies.scala
- projection/src/main/scala/akka/projection/r2dbc/javadsl/R2dbcReplication.scala
- projection/src/main/scala/akka/projection/r2dbc/scaladsl/R2dbcReplication.scala
> feat: Convenience factories for using with Akka Projection gRPC

- projection/src/main/mima-filters/1.1.0-M5.backwards.excludes/pr-366.excludes
- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
- projection/src/test/scala/akka/projection/r2dbc/EventSourcedEndToEndSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcOffsetStoreStateSpec.scala
- projection/src/test/scala/akka/projection/r2dbc/R2dbcTimestampOffsetStoreSpec.scala
Ready for first review round, but I would like to add a test that simulates changing the slice ranges, which is the purpose of this.
References #115
> feat: Keep offset per slice, for change of slice distribution, #115

- projection/src/test/resources/logback-test.xml
Could be good for understanding https://github.com/akka/akka-persistence-r2dbc/issues/371
> chore: enable projection debug logging

- projection/src/main/scala/akka/projection/r2dbc/internal/R2dbcOffsetStore.scala
> chore: reduce keep by slice entries

- .github/workflows/build-test.yml
- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/internal/PayloadCodec.scala
- core/src/main/scala/akka/persistence/r2dbc/journal/JournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/state/scaladsl/DurableStateDao.scala
- core/src/test/scala/akka/persistence/r2dbc/JsonSerializable.scala
- core/src/test/scala/akka/persistence/r2dbc/PayloadSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/TestActors.scala
- core/src/test/scala/akka/persistence/r2dbc/TestConfig.scala
- core/src/test/scala/akka/persistence/r2dbc/cleanup/scaladsl/DurableStateCleanupSpec.scala
* fixed how empty byte array for delete markers are stored
Follow up on https://github.com/akka/akka-persistence-r2dbc/pull/239
cc @odd
> test: Add tests for jsonb as column type for payloads

- docs/src/main/paradox/durable-state-store.md
- docs/src/main/paradox/getting-started.md
- docs/src/main/paradox/index.md
- docs/src/main/paradox/journal.md
- docs/src/main/paradox/postgres_json.md
- docs/src/main/paradox/snapshots.md
- docs/src/test/java/jdocs/home/state/BlogPostJsonColumn.java
- docs/src/test/scala/docs/home/state/BlogPostJsonColumn.scala
> docs: Reference docs for jsonb as column type for payloads

- .github/workflows/nightly.yml
> chore: Scala 3 in nightly

- core/src/main/resources/reference.conf
- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2Dialect.scala
Useful to try things out for us, but probably good for users as well.
> feat: Allow arbitrary H2 options passed through from config

- docs/src/test/resources/application-yugabyte.conf
```
user = "yugabyte"
host = ${?DB_USER}
```
fixed to
```
user = "yugabyte"
user = ${?DB_USER}
```
> [typo] fix "host" -> "user" = ${?DB_USER} in application-yugabyte.conf

- docs/src/test/resources/application-yugabyte.conf
- project/plugins.sbt
> chore: backport some doc updates

- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySliceStartingFromSnapshotSpec.scala
I looked at several logs and tried to reproduce. Didn't find a good explanation other than the test is maybe hitting a case where events are actually not seen, but would have been caught by the backtracking. Backtracking is disabled in this test. Trying to reduce write concurrency.
References #417
> chore: Harden EventsBySliceStartingFromSnapshotSpec, #417

- core/src/main/scala/akka/persistence/r2dbc/internal/h2/H2Dialect.scala
Refs https://github.com/akka/akka-projection/issues/992
See https://github.com/akka/akka-projection/issues/992#issuecomment-1720630672 for details.
> fix(h2): disable optimize reuse results to avoid race condition

- core/src/main/mima-filters/1.2.0-M5.backwards.excludes/r2dbc-session.excludes
- core/src/main/scala/akka/persistence/r2dbc/session/javadsl/R2dbcSession.scala
- core/src/main/scala/akka/persistence/r2dbc/session/scaladsl/R2dbcSession.scala
* javadsl had wrong function type, ApiMayChange so just changed
Similar fixed in https://github.com/akka/akka-projection/pull/1017
> chore: Wrong function type in javadsl.R2dbcSession

- .github/workflows/build-test.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- build.sbt
- project/project-info.conf
See https://github.com/akka/akka/pull/32127
> chore: Drop JDK 8

- project/plugins.sbt
References
- https://github.com/akka/akka-paradox/releases/tag/v0.53
- https://github.com/lightbend/sbt-paradox-dependencies/releases/tag/v0.2.4
> bump: Akka Paradox, Paradox Dependencies

- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerDurableStateDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerJournalDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerQueryDao.scala
- core/src/main/scala/akka/persistence/r2dbc/internal/sqlserver/SqlServerSnapshotDao.scala
As discovered here https://github.com/akka/akka-projection/pull/1122#discussion_r1531862868
> fix: use val for logging in all SqlServer daos

- .fossa.yml
- .github/workflows/build-test.yml
- .github/workflows/fossa.yml
- .github/workflows/native-image-tests.yml
- .github/workflows/nightly.yml
- .github/workflows/publish.yml
- README.md
- docs/release-train-issue-template.md
- project/plugins.sbt
- project/project-info.conf
References https://github.com/lightbend/akka-meta/issues/428
> chore: repo gardening

- project/Dependencies.scala
https://github.com/pgjdbc/r2dbc-postgresql/releases/tag/v1.0.5.RELEASE
> bump: r2dbc-postgresql 1.0.5

- ddl-scripts/create_tables_postgres.sql
- ddl-scripts/create_tables_postgres_0-1.sql
- ddl-scripts/create_tables_postgres_2-3.sql
- ddl-scripts/create_tables_postgres_jsonb.sql
- ddl-scripts/create_tables_sqlserver.sql
- ddl-scripts/create_tables_yugabyte.sql
- docs/src/main/paradox/migration-guide.md
> chore: remove revision from Durable State primary key

- docs/src/main/paradox/data-partition.md
> doc: Describe slice in data partition docs

- LICENSE
- native-image-tests/build.sbt
- project/Dependencies.scala
References https://github.com/akka/akka-persistence-r2dbc/issues/567
> chore: License change date for 1.2.4, Akka 2.9.3 bump

- project/plugins.sbt
Forgot this for the release so will have to backport
> bump: Akka paradox theme 0.57

- core/src/test/scala/akka/persistence/r2dbc/CborSerializable.scala
- core/src/test/scala/akka/persistence/r2dbc/JsonSerializable.scala
- core/src/test/scala/akka/persistence/r2dbc/PayloadSpec.scala
- core/src/test/scala/akka/persistence/r2dbc/TestConfig.scala
- docs/src/main/paradox/data-partition.md
- docs/src/test/java/jdocs/home/sharding/ShardingDocExample.java
- docs/src/test/scala/docs/home/CborSerializable.scala
- docs/src/test/scala/docs/home/sharding/ShardingDocExample.scala
- project/Dependencies.scala
This requires a new Akka release before merging
See https://github.com/akka/akka/pull/32418
> doc: reduce db connections with SliceRangeShardAllocationStrategy

- .github/workflows/nightly.yml
- CONTRIBUTING.md
- docker/docker-compose-yugabyte.yml
Nightly builds failing: https://github.com/akka/akka-persistence-r2dbc/actions/runs/10259141621/job/28383114368
> chore: docker compose

- core/src/test/scala/akka/persistence/r2dbc/query/EventsBySlicePubSubSpec.scala
> test: FilteredPayload with more db partitions, #546

- core/src/main/scala/akka/persistence/r2dbc/internal/BySliceQuery.scala
Mistake in https://github.com/akka/akka-persistence-r2dbc/pull/645
> fix: NoSuchElementException in appendEmptyBucketIfLastIsMissing

- LICENSE
> chore: update change date for 1.3.6
